[package]
name = "yul-sonatina"
version = "0.1.0"
edition = "2021"

[dependencies]
yultsur = { git = "https://github.com/leonardoalt/yultsur", branch = "main" }
sonatina-ir = { path = "../sonatina/crates/ir" }

[dev-dependencies]
dir-test = "0.3.0"
